layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: andrzej-j-5582677b
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Hadoop
    web_url: https://hadoop.apache.org/
    image_url: https://images.squarespace-cdn.com/content/v1/530b4fe4e4b039a663b386ad/1393985701138-APID7N7223YEHX2TT4FD/ke17ZwdGBToddI8pDm48kHYhS3pd-21HXfcygQJ1SCRZw-zPPgdn4jUwVcJE1ZvWQUxwkmyExglNqGp0IvTJZUJFbgE-7XRK3dMEBRBhUpyYvqGxiIL0ypFAT-gwPVZewBlYj_0idMRh4roZbHRbURZC5N9ACxTBGSlCY42crEI/hadoop-logo-square.jpg

  - name: Azure
    web_url: https://azure.microsoft.com/
    image_url: https://blockapps.net/wp-content/uploads/2019/06/microsoft-azure-cloud-small-square.png

  - name: AWS
    web_url: https://aws.amazon.com/
    image_url: https://a0.awsstatic.com/libra-css/images/logos/aws_logo_smile_1200x630.png

  - name: Linux
    web_url: https://www.linuxfoundation.org/
    image_url: https://www.pitt.edu/~jmr250/linux.png

  - name: Gitlab
    web_url: https://www.linuxfoundation.org/
    image_url: https://xebialabs.com/wp-content/uploads/2018/10/GitLab.jpg

  - name: Docker
    web_url: https://www.linuxfoundation.org/
    image_url: https://ih0.redbubble.net/image.363828010.1364/flat,1000x1000,075,f.u1.jpg
    


    
